name: build
on:
  pull_request:
    branches: [ develop, main ]
jobs:
  check-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify repo builds (placeholder)
        run: echo "CI placeholder passed"
